# Question 1

In [674]:
import pandas as pd
import numpy as np

In [675]:
df = pd.read_csv("data.csv")

In [676]:
df.median_house_value

0        452600.0
1        358500.0
2        352100.0
3        341300.0
4        342200.0
           ...   
20635     78100.0
20636     77100.0
20637     92300.0
20638     84700.0
20639     89400.0
Name: median_house_value, Length: 20640, dtype: float64

In [677]:
df.columns


Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity'],
      dtype='object')

In [678]:
df = df[['latitude','longitude','housing_median_age','total_rooms','total_bedrooms','population','households','median_income',
'median_house_value']]

In [679]:
df.head()

latitude  longitude  housing_median_age  total_rooms  total_bedrooms  \
0     37.88    -122.23                41.0        880.0           129.0   
1     37.86    -122.22                21.0       7099.0          1106.0   
2     37.85    -122.24                52.0       1467.0           190.0   
3     37.85    -122.25                52.0       1274.0           235.0   
4     37.85    -122.25                52.0       1627.0           280.0   

   population  households  median_income  median_house_value  
0       322.0       126.0         8.3252            452600.0  
1      2401.0      1138.0         8.3014            358500.0  
2       496.0       177.0         7.2574            352100.0  
3       558.0       219.0         5.6431            341300.0  
4       565.0       259.0         3.8462            342200.0

Question1

In [680]:
#question1
df.isnull().sum()

latitude                0
longitude               0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
dtype: int64

# Question2

In [681]:
#question2
df.population.median()

1166.0

In [682]:
n = len(df_train)

n_val = int(n * 0.2)
n_test = int(n * 0.2)
n_train = n - n_val - n_test

In [683]:
df_train = df.iloc[n_train:]
df_val = df.iloc[n_train:n_train+n_val]
df_test = df.iloc[n_train+n_val:]

In [684]:
np.random.seed(9) #
idx = np.arange(n)

In [685]:
df_train = df.iloc[idx[:n_train]]
df_val = df.iloc[idx[n_train:n_train+n_val]]
df_test = df.iloc[idx[n_train+n_val:]]

In [686]:
df_train.head()

latitude  longitude  housing_median_age  total_rooms  total_bedrooms  \
0     37.88    -122.23                41.0        880.0           129.0   
1     37.86    -122.22                21.0       7099.0          1106.0   
2     37.85    -122.24                52.0       1467.0           190.0   
3     37.85    -122.25                52.0       1274.0           235.0   

   population  households  median_income  median_house_value  
0       322.0       126.0         8.3252            452600.0  
1      2401.0      1138.0         8.3014            358500.0  
2       496.0       177.0         7.2574            352100.0  
3       558.0       219.0         5.6431            341300.0

In [687]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [688]:
df_train.head()

latitude  longitude  housing_median_age  total_rooms  total_bedrooms  \
0     37.88    -122.23                41.0        880.0           129.0   
1     37.86    -122.22                21.0       7099.0          1106.0   
2     37.85    -122.24                52.0       1467.0           190.0   
3     37.85    -122.25                52.0       1274.0           235.0   

   population  households  median_income  median_house_value  
0       322.0       126.0         8.3252            452600.0  
1      2401.0      1138.0         8.3014            358500.0  
2       496.0       177.0         7.2574            352100.0  
3       558.0       219.0         5.6431            341300.0

In [689]:
y_train = np.log1p(df_train.median_house_value.values) # to numpy
y_val = np.log1p(df_val.median_house_value.values) # to numpy
y_test = np.log1p(df_test.median_house_value.values) # to numpy

In [690]:
del df_train['median_house_value']
del df_val['median_house_value']
del df_test['median_house_value']

# Question3


In [691]:
df_train.total_bedrooms.mean()

415.0

In [692]:
#fill out of 0
X_train = df_train.fillna(0).values

In [693]:
def train_linear_regression(X, y):
  ones = np.ones(X.shape[0])
  X = np.column_stack([ones, X])

  XTX = X.T.dot(X)
  XTX_inv = np.linalg.inv(XTX)
  w_full = XTX_inv.dot(X.T).dot(y)

  return w_full[0], w_full[1:]

In [698]:
X_train

array([[ 3.7880e+01, -1.2223e+02,  4.1000e+01,  8.8000e+02,  1.2900e+02,
         3.2200e+02,  1.2600e+02,  8.3252e+00],
       [ 3.7860e+01, -1.2222e+02,  2.1000e+01,  7.0990e+03,  1.1060e+03,
         2.4010e+03,  1.1380e+03,  8.3014e+00],
       [ 3.7850e+01, -1.2224e+02,  5.2000e+01,  1.4670e+03,  1.9000e+02,
         4.9600e+02,  1.7700e+02,  7.2574e+00],
       [ 3.7850e+01, -1.2225e+02,  5.2000e+01,  1.2740e+03,  2.3500e+02,
         5.5800e+02,  2.1900e+02,  5.6431e+00]])

In [699]:
y_train

array([13.02276622, 12.78968673, 12.77167335, 12.74052006])

In [672]:
w0, w =train_linear_regression(X_train, y_train)

LinAlgError: ignored

In [673]:
y_pred = w0 + X_train.dot(w)

ValueError: ignored

In [664]:
def rmse(y, y_pred):
  error = y - y_pred
  se = error ** 2
  mse = se.mean()
  return np.sqrt(mse)


In [666]:
round(rmse(y_train, y_pred),2)

90.89

0.17 if we fill out of 0; 
0.18 if we rill out of mean

# Question 4

In [211]:
def train_linear_regression_reg(X, y, r=0.001):
  ones = np.ones(X.shape[0])
  X = np.column_stack([ones, X])

  XTX = X.T.dot(X)
  XTX = XTX + r *np.eye(XTX.shape[0])

  XTX_inv = np.linalg.inv(XTX)
  w_full = XTX_inv.dot(X.T).dot(y)

  return w_full[0], w_full[1:]

In [215]:
X_val = df_val

In [222]:
for r in [0, 0.000001, 0.0001, 0.001, 0.01, 0.1, 1, 5, 10]:
  w0, w =train_linear_regression_reg(X_train, y_train, r)

  y_pred = w0 + X_val.dot(w)
  score = rmse(y_val, y_pred)

  print(r, ' ', round(score,5))

0   0.18013
1e-06   0.18013
0.0001   0.18013
0.001   0.18011
0.01   0.17996
0.1   0.17932
1   0.17927
5   0.17939
10   0.17941


# Question 5

In [ ]:
0.16, 0.12, 0.1, 0.1, 0.1, 0.1, 0.08, 0.07, 0.06, 0.03

In [455]:
np.std([0.16, 0.12, 0.1, 0.1, 0.1, 0.1, 0.08, 0.07, 0.06, 0.03])

0.033406586176980134

In [456]:
round(0.033406586176980134, 3)

0.033

# Question6

In [457]:
df_full_train = pd.concat([df_train, df_val])

In [459]:
df_full_train.head()

latitude  longitude  housing_median_age  total_rooms  total_bedrooms  \
0     37.88    -122.23                41.0        880.0           129.0   
1     37.86    -122.22                21.0       7099.0          1106.0   
2     37.85    -122.24                52.0       1467.0           190.0   
3     37.85    -122.25                52.0       1274.0           235.0   
4     37.85    -122.25                52.0       1627.0           280.0   

   population  households  median_income  median_house_value  
0       322.0       126.0         8.3252            452600.0  
1      2401.0      1138.0         8.3014            358500.0  
2       496.0       177.0         7.2574            352100.0  
3       558.0       219.0         5.6431            341300.0  
4       565.0       259.0         3.8462            342200.0

In [460]:
df_full_train.reset_index(drop= True)

latitude  longitude  housing_median_age  total_rooms  total_bedrooms  \
0      37.88    -122.23                41.0        880.0           129.0   
1      37.86    -122.22                21.0       7099.0          1106.0   
2      37.85    -122.24                52.0       1467.0           190.0   
3      37.85    -122.25                52.0       1274.0           235.0   
4      37.85    -122.25                52.0       1627.0           280.0   
5      37.85    -122.25                52.0        919.0           213.0   
6      37.84    -122.25                52.0       2535.0           489.0   
7      37.84    -122.25                52.0       3104.0           687.0   
8      37.84    -122.26                42.0       2555.0           665.0   
9      37.84    -122.25                52.0       3549.0           707.0   
10     37.85    -122.26                52.0       2202.0           434.0   
11     37.85    -122.26                52.0       3503.0           752.0   
12     37.85    -122.26                52.0       2491.0           474.0   
13     37.84    -122.26                52.0        696.0           191.0   
14     37.85    -122.26                52.0       2643.0           626.0   
15     37.85    -122.26                50.0       1120.0           283.0   
16     37.85    -122.27                52.0       1966.0           347.0   
17     37.85    -122.27                52.0       1228.0           293.0   
18     37.84    -122.26                50.0       2239.0           455.0   
19     37.84    -122.27                52.0       1503.0           298.0   
20     37.85    -122.27                40.0        751.0           184.0   
21     37.85    -122.27                42.0       1639.0           367.0   
22     37.84    -122.27                52.0       2436.0           541.0   

    population  households  median_income  median_house_value  
0        322.0       126.0         8.3252            452600.0  
1       2401.0      1138.0         8.3014            358500.0  
2        496.0       177.0         7.2574            352100.0  
3        558.0       219.0         5.6431            341300.0  
4        565.0       259.0         3.8462            342200.0  
5        413.0       193.0         4.0368            269700.0  
6       1094.0       514.0         3.6591            299200.0  
7       1157.0       647.0         3.1200            241400.0  
8       1206.0       595.0         2.0804            226700.0  
9       1551.0       714.0         3.6912            261100.0  
10       910.0       402.0         3.2031            281500.0  
11      1504.0       734.0         3.2705            241800.0  
12      1098.0       468.0         3.0750            213500.0  
13       345.0       174.0         2.6736            191300.0  
14      1212.0       620.0         1.9167            159200.0  
15       697.0       264.0         2.1250            140000.0  
16       793.0       331.0         2.7750            152500.0  
17       648.0       303.0         2.1202            155500.0  
18       990.0       419.0         1.9911            158700.0  
19       690.0       275.0         2.6033            162900.0  
20       409.0       166.0         1.3578            147500.0  
21       929.0       366.0         1.7135            159800.0  
22      1015.0       478.0         1.7250            113900.0

In [461]:
y_full_train = np.concatenate([y_train, y_val])

In [462]:
y_full_train

array([13.02276622, 12.78968673, 12.77167335, 12.74052006, 12.74315356,
       12.50506922, 12.60887087, 12.39421473, 12.33138725, 12.47266258,
       12.54789128, 12.39587035, 12.2713968 , 12.16160338, 11.97792283,
       11.84940484, 11.93492643, 11.95440744, 11.97477721, 12.00089793,
       11.90159023, 11.98168457, 11.64308493])

In [466]:
X_full_train = df_full_train

In [467]:
w0, w =train_linear_regression_reg(X_full_train, y_full_train, r =0.001)

In [469]:
X_test =df_test
y_pred = w0 + X_test.dot(w)
score = rmse(y_test, y_pred)
score

0.15327540293946154